---
title: "Mc4r in postnatal mouse PVN"
author: "Evgenii Tretiakov"
date: "2021-05-18"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    autodep        = TRUE,
    cache          = FALSE,
    cache.lazy     = FALSE,
    dev            = c("png", "pdf"),
    echo           = FALSE,
    error          = FALSE,
    fig.align      = "center",
    fig.width      = 14,
    fig.height     = 12,
    message        = FALSE,
    warning        = FALSE
)

# Load tidyverse infrastructure packages
suppressPackageStartupMessages({
    library(here)
    library(tidyverse)
    library(magrittr)
    library(future)
    library(kableExtra)
})

if (!requireNamespace("Nebulosa", quietly = TRUE)) BiocManager::install("Nebulosa")
# Load packages for scRNA-seq analysis and visualisation
suppressPackageStartupMessages({
    library(Seurat)
    library(SeuratWrappers)
    library(SeuratDisk)
    library(pagoda2)
    library(conos)
    library(UpSetR)
    library(patchwork)
    library(Nebulosa)
})

# Set paths
src_dir    <- here::here('code')
data_dir   <- here::here('data')
output_dir <- here::here('output')
plots_dir  <- here::here(output_dir, 'figures')
tables_dir <- here::here(output_dir, 'tables')
source(here::here(src_dir, 'main.R'))
source(here::here(src_dir, 'genes.R'))

# set seed
reseed <- 42
set.seed(seed = reseed)

# available cores
n.cores <- 12

# Parameters for parallel execution
plan("multiprocess", workers = n.cores)
options(future.globals.maxSize = Inf,
        future.rng.onMisuse = "ignore")
plan()

# ggplot2 theme
theme_set(theme_bw())
```

```{r load-data, include=FALSE}
try({
  tibble(
    name = c(
      "rar2020.srt.pub.all",
      "rar2020.srt.pub",
      "rar2020.srt.pvn.bck",
      "rar2020.srt.pvn"
    ),
    file = c(
      '2021-05-13_001-086-446-605-669_mm10-hypothalamus_srt4-obj-umap.rds',
      '2021-05-13_001-086-446-605-669_adult_mm10-hypothalamus_srt4-obj-umap.rds',
      '2021-05-13_001-086-446-605-669_adult_mm10-hypothalamus-pvn_alk-thinness-paper-subset-srt4-obj-umap.rds',
      '2021-05-13_001-086-446-605-669_adult_mm10-hypothalamus-pvn_bottom-lh-excl-srt4-obj-sct-umap.rds'
    )
  ) %>% pwalk(., readRDS)
  
  tibble(
    name = c(
      "all_markers_pvn_wtree_final",
      "srt_mcrs",
      "plot_data",
      "plot_data_filt",
      "plot_data3"
    ),
    file = c(
      '2021-05-13_001-086-446-605-669_adult_mm10-hypothalamus-pvn_deg-mrk-gns-ctypes-by-sct-wilcox.csv',
      '2021-05-13_001-086-446-605-669_adult_mm10-hypothalamus-pvn_expr-mtx-cells-by-mrk-gns-int.csv',
      '2021-05-13_001-086-446-605-669_adult_mm10-hypothalamus-pvn_ncells-long-by-mrk-gns-int.csv',
      '2021-05-13_001-086-446-605-669_adult_mm10-hypothalamus-pvn-mc4r-pos_ncells-long-by-mrk-gns-int.csv',
      '2021-05-13_001-086-446-605-669_adult_mm10-hypothalamus-pvn_ncells-long-by-mrk-gns-int-ctypes.csv'
    )
  ) %>% pwalk(., readTable)
  
  srt_mcrs %<>% column_to_rownames(var = "cell_names")
  
}
)

```

```{r check-data-load, include=FALSE}
check.data <- 
    c("rar2020.srt.pub", "rar2020.srt.pvn", "rar2020.srt.pvn.bck",
      "plot_data", "plot_data_filt", "plot_data3",
      "all_markers_pvn_wtree_final", "srt_mcrs") %>% 
    purrr::map_lgl(~ exists(x = .x))

stopifnot(all(check.data))

```

## Published subset of adult hypothalamic data (Nature + Cell datasets) in UMAP (cells similarity) space

```{r published-adult-sc-hypothalamus, fig.width=14, fig.height=12, echo=FALSE, warning=FALSE}
Idents(rar2020.srt.pub) <- "wtree"
colours <- readr::read_lines(here(data_dir, "colours_wtree.tsv"))
clrlev <- 1:45
names(colours) <- clrlev
pvn.cols <- colours[c(15, 24, 26, 31, 43)]

Idents(rar2020.srt.pub.all) <- "wtree"
rar2020.srt.pub.pne <- 
    rar2020.srt.pub.all %>% 
    subset(idents = c(24))


DimPlot(rar2020.srt.pub, label = TRUE, cols = colours, repel = TRUE) + DarkTheme()

```

## Density of expression for MC-R gene family in UMAP space

```{r plot-density-mcrs-on-original-umap, fig.width=28, fig.height=24, dpi=300, echo=FALSE, warning=FALSE}
p.d <- plot_density(rar2020.srt.pub, "Mc4r") + DarkTheme()
p.c <- plot_density(rar2020.srt.pub, "Mc3r") + DarkTheme()
p.b <- plot_density(rar2020.srt.pub, "Mc2r") + DarkTheme()
p.a <- plot_density(rar2020.srt.pub, "Mc1r") + DarkTheme()
(p.a + p.b)/(p.c + p.d)
```

## Zoom into area of highest density of Mc4r expressing cells in UMAP space (PNe of PVN)

```{r plot-density-mc4r-umap, fig.width=30, fig.height=24, echo=FALSE, dpi=200, warning=FALSE}
pwlayout <- "
AABB
AABB
DDCC
DDCC
"
p1 <- plot_density(rar2020.srt.pvn, "Mc4r") + DarkTheme()

p2Trh <- FeaturePlot(
    rar2020.srt.pvn,
    features = c("Mc4r", "Trh"),
    slot = "scale.data",
    order = TRUE,
    blend = TRUE,
    blend.threshold = 0.1,
    combine = FALSE
)

p2 <- p2Trh[[3]] + 
    NoLegend() + 
    DarkTheme()

p2Crh <- FeaturePlot(
    rar2020.srt.pvn,
    features = c("Mc4r", "Crh"),
    slot = "scale.data",
    order = TRUE,
    blend = TRUE,
    blend.threshold = 0.1,
    combine = FALSE
)

p3 <- p2Crh[[3]] + 
    NoLegend() + 
    DarkTheme()

p4 <- p2Trh[[1]] + NoLegend() + DarkTheme()

p6 <- p2Trh[[4]] + NoLegend() + DarkTheme()
p7 <- p2Crh[[4]] + NoLegend() + DarkTheme()


p1 + p4 + p2 + p3 + p6 + p7 + plot_layout(design = pwlayout)
```

## Age dynamic

```{r plot-mc4r-corr-scaterplot-by-age, fig.width=16, fig.height=14, echo=FALSE, dpi=350, warning=FALSE}
rar2020.srt.pub.pne <-
    SCTransform(rar2020.srt.pub.pne,
                variable.features.n = 3000,
                vars.to.regress = c("log_umi_per_gene"),
                return.only.var.genes = FALSE,
                seed.use = reseed,
                verbose = FALSE)
srt_mcrs_filtered_ages <-
    GetAssayData(rar2020.srt.pub.pne, 'data', 'SCT') %>%
    as.data.frame() %>%
    t()
filt_age_pvn_sum <- 
    colSums(srt_mcrs_filtered_ages) %>% 
    .[. > 5] %>% 
    names()
srt_mcrs_filtered_ages %<>% .[, filt_age_pvn_sum]

minim_pvn_age_filt <- 
    srt_mcrs_filtered_ages %>% 
    as_tibble() %>% 
    select(all_of(filt_age_pvn_sum)) %>% 
    summarise(across(.fns = function(x) quantile(x, .1)))

minim_pvn_age_filt2 <-
    (srt_mcrs_filtered_ages > as.double(minim_pvn_age_filt)) %>%
    as_tibble() %>%
    mutate_all(as.numeric) %>% 
    summarise(across(.fns = function(x) sum(x)/length(x))) %>% 
    as_vector() %>% 
    .[.['Mc4r'] <= .]

srt_mcrs_filtered_ages %<>% .[, names(minim_pvn_age_filt2)]
pvn_age_corr_genes  <- corrr::correlate(srt_mcrs_filtered_ages)

mcrs_age_corr_genes <- 
    pvn_age_corr_genes %>% 
    arrange(-Mc4r) %>% 
    select(term, Mc4r, Trh)

threshold.min.pct.Trh  <- .05
threshold.min.pct.Mc4r <- .1
threshold.max.pct.Trh  <- .05
threshold.max.pct.Mc4r <- .1
mcrs_age_corr_genes_intersect_1 <- 
    intersect(x = mcrs_age_corr_genes %>% 
                slice_max(order_by = Trh, 
                          prop = threshold.min.pct.Trh), 
              y = mcrs_age_corr_genes %>% 
                slice_max(order_by = Mc4r, 
                          prop = threshold.min.pct.Mc4r)
)
mcrs_age_corr_genes_intersect_2 <- 
    intersect(x = mcrs_age_corr_genes %>% 
                slice_min(order_by = Trh, 
                          prop = threshold.max.pct.Trh), 
              y = mcrs_age_corr_genes %>% 
                slice_min(order_by = Mc4r, 
                          prop = threshold.max.pct.Mc4r)
)
highlight_mcrs_age_corr_genes <- 
    union(mcrs_age_corr_genes_intersect_1$term,
          mcrs_age_corr_genes_intersect_2$term)

# require("biomartr")
# mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl")
# union(c("Slc2a3", "Slc17a6", "Gad1", "Slc32a1", 
#         "Irs1", "Ltk", "Lepr", "Alk", "Lmo4", 
#         "Mdk", "Ptn", "Sim1", 
#         "Fam150a", "Fam150b", "Slc1a2"), 
#       union(good_npeprec_final_full, 
#             good_neuropept_final_full)) %>%
#   biomart(
#     genes = .,
#     mart = "ENSEMBL_MART_ENSEMBL",
#     dataset = "mmusculus_gene_ensembl",
#     attributes = c("ensembl_gene_id", "description"),
#     filters = "mgi_symbol"
#   ) %>% as_tibble() -> full_names_tab
# readr::write_csv(full_names_tab, path = file.path(tables_dir, 'full_names_tab.csv'))


param.plot.1.repel.box.padding       <- 0.5
param.plot.1.repel.max.overap        <- 10
param.plot.1.filter.padj             <- 0.01
param.plot.1.filter.baseMean         <- 1
param.plot.1.point.colour.background <- "grey50"

plot_corr_mcrs_age_corr_genes <- 
  mcrs_age_corr_genes %>%
  mutate(term = if_else(condition = term %in% highlight_mcrs_age_corr_genes, term, "")) %>% 
  ggplot(., aes(Mc4r, Trh, label = term)) +
  geom_point(data = mcrs_age_corr_genes[!mcrs_age_corr_genes$term %in% highlight_mcrs_age_corr_genes,], 
             color = param.plot.1.point.colour.background) +
  ggrepel::geom_text_repel(box.padding = param.plot.1.repel.box.padding, 
                           max.overlaps = param.plot.1.repel.max.overap) +
  geom_point(data = mcrs_age_corr_genes[mcrs_age_corr_genes$term %in% mcrs_age_corr_genes_intersect_1$term,], 
             color = "red") +
  geom_point(data = mcrs_age_corr_genes[mcrs_age_corr_genes$term %in% mcrs_age_corr_genes_intersect_2$term,], 
             color = "blue") +
  labs(title = "pnePVN cells correlation with Mc4r and Trh",
       caption = sprintf("Selected genes (red) within intersection of top %s correlation with Trh and top %s correlation with Trh\n(blue) within intersection of bottom %s correlation with Trh and bottom %s correlation with Trh;\ngenes with same or higher percent of expressing cells as Mc4r",
                         threshold.min.pct.Trh,
                         threshold.min.pct.Mc4r,
                         threshold.max.pct.Trh,
                         threshold.max.pct.Mc4r))

plot_corr_mcrs_age_corr_genes
```

```{r kable-mc4r-corr-by-age}
mcrs_age_corr_genes[mcrs_age_corr_genes$term %in% highlight_mcrs_age_corr_genes,] %>% 
  arrange(-Mc4r) %>%
  kbl(caption = sprintf("Selected genes are within intersection of top %s correlation with Trh and top %s correlation with Trh\nand within intersection of bottom %s correlation with Trh and bottom %s correlation with Trh;\ngenes with same or higher percent of expressing cells as Mc4r",
                        threshold.min.pct.Trh,
                        threshold.min.pct.Mc4r,
                        threshold.max.pct.Trh,
                        threshold.max.pct.Mc4r),
      digits = 2) %>% 
  kable_paper() %>%
  scroll_box(width = "100%", height = "200px")
```


```{r plot-mc4r-heatmap-by-age, fig.width=12, fig.asp=2, echo=FALSE, dpi=300, warning=FALSE}
plot_heatmap_mcrs_age_corr_genes <- 
  DoHeatmap(
    rar2020.srt.pub.pne,
    features = c('Mc4r', highlight_mcrs_age_corr_genes),
    size = 3,
    assay = 'SCT',
    slot = 'scale.data',
    group.by = "age"
  )

plot_heatmap_mcrs_age_corr_genes
```

```{r plot-mc4r-dotplot-by-age, fig.width=32, fig.asp=0.4, echo=FALSE, dpi=200, warning=FALSE}
plot_dot_mcrs_age_corr_genes <- 
  DotPlot(
    rar2020.srt.pub.pne,
    assay = "SCT",
    features = c('Mc4r', highlight_mcrs_age_corr_genes),
    group.by = "age"
  ) + RotatedAxis()

plot_dot_mcrs_age_corr_genes
```


## Gene Combinations

```{r plot-heatmap-adult, fig.width=7, fig.height=6, echo=FALSE}
rar2020.srt.pub.pne %<>% subset(subset = age %in% c("P10", "P23"))

markers_wtree_final_trh <- union(
  all_markers_pvn_wtree_final %>%
    dplyr::filter(cluster %in% c('pneTRH'), 
                  p_val <= 1e-8) %>% 
    mutate(pct.dif = pct.1 - pct.2) %>% 
    arrange(-pct.dif) %>% 
    filter(pct.dif > .1, 
           pct.2 >= .5, 
           avg_log2FC >= .5, 
           gene %in% big_genes) %>% 
    arrange(-avg_log2FC) %>% 
    .$gene,
  all_markers_pvn_wtree_final %>%
    dplyr::filter(cluster %in% c('pneTRH'), 
                  p_val_adj <= 1e-5) %>% 
    mutate(pct.dif = pct.1 - pct.2) %>% 
    arrange(-pct.dif) %>% 
    filter(pct.dif > .1, 
           pct.2 >= .5, 
           avg_log2FC >= 1.5) %>% 
    arrange(-avg_log2FC) %>% 
    .$gene
)

markers_wtree_final_pvn <- union(
  all_markers_pvn_wtree_final %>%
    dplyr::filter(cluster %in% c('pneCRH'), 
                  p_val <= 1e-4) %>% 
    mutate(pct.dif = pct.1 - pct.2) %>% 
    arrange(-pct.dif) %>% 
    filter(pct.dif > .1, 
           pct.1 >= .1, 
           avg_log2FC >= .15, 
           gene %in% big_genes) %>% 
    arrange(-avg_log2FC) %>% 
    .$gene,
  all_markers_pvn_wtree_final %>%
    dplyr::filter(cluster %in% c('pneCRH'), 
                  p_val_adj <= 1e-3) %>% 
    mutate(pct.dif = pct.1 - pct.2) %>% 
    arrange(-pct.dif) %>% 
    filter(pct.dif > .1, 
           pct.1 >= .1, 
           avg_log2FC >= 1) %>% 
    arrange(-avg_log2FC) %>% 
    .$gene
)

mcrs_age_corr_genes_intersect_3 <- 
  unique(
    c(
      markers_wtree_final_trh,
      intersect(x = mcrs_age_corr_genes %>% 
                  slice_max(order_by = Trh, 
                            n = 25), 
                y = mcrs_age_corr_genes %>% 
                  slice_max(order_by = Mc4r, 
                            n = 25))$term, 
      mcrs_age_corr_genes %>% 
        slice_max(order_by = Trh, n = 3) %>% 
        filter(Mc4r >= 0.1) %>% 
        .$term,
      mcrs_age_corr_genes %>% 
        slice_max(order_by = Mc4r, prop = 0.01) %>% 
        filter(Trh >= 0.3) %>% 
        .$term,
      markers_wtree_final_pvn,
      'Mc4r',
      'Ptn',
      'Alk',
      pvn_genes,
      dmh_trh_g
      )
    )

srt_mcrs_filtered <-
    GetAssayData(rar2020.srt.pub.pne, 'data', 'SCT') %>%
    as.data.frame() %>%
    .[unique(c(mcrs_age_corr_genes_intersect_3)) %>%
          .[. %in% row.names(rar2020.srt.pub.pne@assays$SCT@data)], ] %>%
    as.data.frame() %>%
    t()

custom_genes <- c(corrr::correlate(srt_mcrs_filtered) %>% arrange(Mc4r) %>% select(term, Mc4r) %>% .$term)

custom_order <- 
  srt_mcrs_filtered %>%
  as.data.frame() %>% 
  rownames_to_column(var = 'cname') %>% 
  select(cname, Mc4r, Opcml, Trh, Nell2, 
          Brinp3, Irs4, Lrfn5, Gpr101, 
          Mbnl2, Nr3c2, Pura, Mbnl3, 
          Ptn, Rora, Fos, Ghr, Ebf3, 
          Cartpt, Nrxn3, Sstr2, 
          Alk, Scgn,
          Crh, Pgf) %>% 
  arrange(-Mc4r, -Opcml, -Trh, -Nell2, 
          -Brinp3, -Irs4, -Lrfn5, -Gpr101, 
          -Mbnl2, -Nr3c2, -Pura, -Mbnl3, 
          Ptn, Rora, Fos, Ghr, Ebf3, 
          Cartpt, Nrxn3, Sstr2, 
          Alk, Scgn,
          Crh, Pgf) %>% 
  .$cname

p <- DoHeatmap(rar2020.srt.pub.pne, cells = custom_order, features = custom_genes, size = 3, assay = 'SCT', slot = 'scale.data')
p
```

```{r plot-upset-5, fig.width=7, fig.height=6, echo=FALSE}
upset(as.data.frame(plot_data_filt), order.by = 'freq',
      sets.x.label = 'Number of cells',
      text.scale = c(2, 1.6, 2, 1.3, 2, 3),
      nsets = 5)
```

```{r plot-upset-16, fig.width=12, fig.height=9, echo=FALSE}
minim <- 
  srt_mcrs_filtered %>% 
  as_tibble() %>% 
  dplyr::summarise(across(.fns = function(x) quantile(x, .1)))

plot_data <-
    (srt_mcrs_filtered > as.double(minim)) %>%
    as_tibble() %>%
    mutate_all(as.numeric)

upset(as.data.frame(plot_data), order.by = 'freq',
      sets.x.label = 'Number of cells',
      text.scale = c(2, 1.6, 2, 1.3, 2, 3),
      nsets = 10,
      sets = c('Trh', 'Crh', 'Mc4r', 
               'Ptn', 'Pura', 'Rora', 
               'Scgn', 'Ebf3', 'Nr3c2', 
               'Irs4', 'Gpr101', 'Sstr2', 
               'Ghr', 'Opcml', 'Alk', 'Slc1a4'),
      nintersects = 60)
```

```{r plot-upset-10, fig.width=8, fig.height=7, echo=FALSE}
upset(as.data.frame(plot_data), order.by = 'freq',
      sets.x.label = 'Number of cells',
      text.scale = c(2, 1.6, 2, 1.3, 2, 3),
      nsets = 10,
      sets = mcrs_age_corr_genes %>% 
        filter(term %in% (plot_data %>% 
                            colSums() %>% 
                            sort() %>% 
                            names())) %>% 
        arrange(-Mc4r) %>% 
        .$term %>% 
        head(9) %>% 
        c("Mc4r", .),
      nintersects = 60)
```

